refactor(lint): solve lint issues related to non used variables

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,5 +4,5 @@ GREEN='\033[0;32m'
 BOLD='\033[1m'
 RESET='\033[0m'
 
-echo '' || { echo "${RED}${BOLD}Commit aborted:${RESET} ${BOLD}Linting failed.${RESET}"; false; }
+npm run lint || { echo "${RED}${BOLD}Commit aborted:${RESET} ${BOLD}Linting failed.${RESET}"; false; }
 echo "${GREEN}${BOLD}Pre-commit success:${RESET} ${BOLD}Linting success.${RESET}" || true
